"""Command-line interface (CLI) for Agent Visual Bridge."""

from __future__ import annotations

import argparse
import json
import sys
import webbrowser
from pathlib import Path
from typing import Any, Dict

from agent_visual_bridge.core import VisualBridge
from agent_visual_bridge.parser import parse_html_file
from agent_visual_bridge.watcher import serve_and_wait, watch_html_file


def _cmd_auto(args: argparse.Namespace) -> int:
    """Auto-detect format, generate HTML, and optionally wait for human feedback."""
    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: Input file not found: {input_path}", file=sys.stderr)
        return 1

    try:
        raw_data = json.loads(input_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"Error: Failed to parse JSON from {input_path}: {e}", file=sys.stderr)
        return 1

    output_path = Path(args.output or input_path.with_suffix(".html"))
    bridge = VisualBridge.from_data(raw_data, report_type=args.type)
    bridge.save_html(output_path)

    print(f"✅ Generated {bridge.report_type.value.upper()} report -> {output_path}")

    if args.open and not args.serve:
        try:
            webbrowser.open(output_path.resolve().as_uri())
        except Exception:
            pass

    if args.serve:
        print(f"🌐 Ephemeral server active. Waiting for human submission on {output_path.name}...")
        try:
            result = serve_and_wait(output_path, open_browser=args.open, timeout=args.timeout)
            _handle_feedback_output(result, args.feedback_out)
        except TimeoutError:
            print("⚠️ Timeout waiting for human submission.", file=sys.stderr)
            return 2
    elif args.watch:
        print(f"👀 Watching {output_path.name} for human save...")
        try:
            result = watch_html_file(output_path, timeout=args.timeout)
            _handle_feedback_output(result, args.feedback_out)
        except TimeoutError:
            print("⚠️ Timeout waiting for file update.", file=sys.stderr)
            return 2

    return 0


def _cmd_read(args: argparse.Namespace) -> int:
    """Parse human feedback from an HTML report."""
    html_path = Path(args.html_file)
    if not html_path.exists():
        print(f"Error: File not found: {html_path}", file=sys.stderr)
        return 1

    data = parse_html_file(html_path)

    if args.markdown:
        print(data["mandate_markdown"])
    elif args.output:
        out_p = Path(args.output)
        out_p.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"✅ Feedback extracted to {out_p}")
    else:
        # Print summary and decisions
        summary = data["summary"]
        print(f"📊 Summary for {html_path.name}:")
        print(f"  Total items : {summary['total']}")
        print(f"  Validated   : {summary['validated']}")
        print(f"  Adjusted    : {summary['adjusted']}")
        print(f"  Pending     : {summary['pending']}\n")

        if data["adjusted"]:
            print("✏️ Adjustments / Remarks:")
            for item in data["adjusted"]:
                print(f"  - [{item['id']}] {item.get('title', '')}")
                if item.get("remark"):
                    print(f"    > {item['remark']}")
                if item.get("options"):
                    print(f"    Options: {', '.join(item['options'])}")
        print("\nUse --markdown to display full prompt or -o to export JSON.")

    return 0


def _cmd_watch(args: argparse.Namespace) -> int:
    """Watch an HTML file until the human user saves it."""
    html_path = Path(args.html_file)
    if not html_path.exists():
        print(f"Error: File not found: {html_path}", file=sys.stderr)
        return 1

    print(f"👀 Watching {html_path.name} (timeout: {args.timeout}s)...")
    try:
        data = watch_html_file(html_path, timeout=args.timeout)
        _handle_feedback_output(data, args.output)
        return 0
    except TimeoutError:
        print("⚠️ Timed out waiting for human save.", file=sys.stderr)
        return 2


def _cmd_serve(args: argparse.Namespace) -> int:
    """Serve HTML on ephemeral HTTP port and wait for 1-click submit."""
    html_path = Path(args.html_file)
    if not html_path.exists():
        print(f"Error: File not found: {html_path}", file=sys.stderr)
        return 1

    print(f"🌐 Serving {html_path.name}...")
    try:
        data = serve_and_wait(html_path, port=args.port, open_browser=args.open, timeout=args.timeout)
        _handle_feedback_output(data, args.output)
        return 0
    except TimeoutError:
        print("⚠️ Timed out waiting for human submission.", file=sys.stderr)
        return 2


def _cmd_init(args: argparse.Namespace) -> int:
    """Generate a starter JSON template."""
    rtype = args.type.lower()
    template: Dict[str, Any] = {"title": f"New {rtype.title()} Template", "subtitle": "Generated by agent-bridge"}

    if rtype == "audit":
        template["items"] = [
            {"id": "check-1", "title": "Database transaction isolation", "severity": "high", "description": "Ensure atomic blocks around writes."},
            {"id": "check-2", "title": "Endpoint rate limiting", "severity": "medium", "description": "Verify rate limits on public routes."}
        ]
    elif rtype == "plan":
        template["items"] = [
            {"id": "lot-1", "title": "Backend Models & Migrations", "lot": "Lot 1", "description": "Update schema and run safe migrations."},
            {"id": "lot-2", "title": "API Serializers & Views", "lot": "Lot 2", "description": "Wire views with permission guards."}
        ]
    elif rtype == "review":
        template["items"] = [
            {"id": "file-1", "title": "auth/views.py", "description": "Refactored token refresh logic and session revocation."}
        ]
    else:
        template["items"] = [
            {"id": "decision-1", "title": "Database Engine", "description": "Choose between PostgreSQL and SQLite for development."}
        ]

    out_p = Path(args.output or f"sample_{rtype}.json")
    out_p.write_text(json.dumps(template, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"✅ Starter template created: {out_p}")
    return 0


def _handle_feedback_output(result: Dict[str, Any], output_path: str | None) -> None:
    """Save or display feedback result."""
    if output_path:
        out_p = Path(output_path)
        out_p.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"✅ Human feedback written to: {out_p}")
    else:
        print("🎉 Human feedback received:")
        if "summary" in result:
            s = result["summary"]
            print(f"   Validated: {s.get('validated', 0)}, Adjusted: {s.get('adjusted', 0)}, Pending: {s.get('pending', 0)}")
        elif "decisions" in result:
            print(f"   Decisions count: {len(result['decisions'])}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="agent-bridge",
        description="Agent Visual Bridge — Human-in-the-loop visual arbitration for AI agents.",
    )
    subparsers = parser.add_subparsers(dest="command", help="Available subcommands")

    # auto
    p_auto = subparsers.add_parser("auto", help="Auto-detect format and generate HTML report")
    p_auto.add_argument("input", help="Path to input JSON file")
    p_auto.add_argument("-o", "--output", help="Output HTML file path")
    p_auto.add_argument("-t", "--type", choices=["audit", "plan", "review", "decision"], help="Force specific type")
    p_auto.add_argument("--open", dest="open", action="store_true", default=True, help="Open in browser")
    p_auto.add_argument("--no-open", dest="open", action="store_false", help="Do not open browser")
    p_auto.add_argument("--watch", action="store_true", help="Wait for user file save")
    p_auto.add_argument("--serve", action="store_true", help="Start ephemeral server and wait for submit")
    p_auto.add_argument("--timeout", type=float, default=600.0, help="Wait timeout in seconds")
    p_auto.add_argument("--feedback-out", help="Path to output feedback JSON")

    # read
    p_read = subparsers.add_parser("read", help="Parse saved HTML report and extract human decisions")
    p_read.add_argument("html_file", help="Path to HTML report")
    p_read.add_argument("-o", "--output", help="Path to save JSON feedback")
    p_read.add_argument("--markdown", action="store_true", help="Print ready-to-use markdown prompt")

    # watch
    p_watch = subparsers.add_parser("watch", help="Watch HTML file until user saves changes")
    p_watch.add_argument("html_file", help="Path to HTML report")
    p_watch.add_argument("-o", "--output", help="Output JSON path")
    p_watch.add_argument("--timeout", type=float, default=600.0, help="Timeout in seconds")

    # serve
    p_serve = subparsers.add_parser("serve", help="Serve HTML on ephemeral server and wait for 1-click submit")
    p_serve.add_argument("html_file", help="Path to HTML report")
    p_serve.add_argument("-p", "--port", type=int, default=0, help="Port (0 for ephemeral)")
    p_serve.add_argument("-o", "--output", help="Output JSON path")
    p_serve.add_argument("--open", dest="open", action="store_true", default=True, help="Open browser")
    p_serve.add_argument("--no-open", dest="open", action="store_false", help="Do not open browser")
    p_serve.add_argument("--timeout", type=float, default=600.0, help="Timeout in seconds")

    # init
    p_init = subparsers.add_parser("init", help="Generate starter JSON template")
    p_init.add_argument("type", choices=["audit", "plan", "review", "decision"], help="Template type")
    p_init.add_argument("-o", "--output", help="Output JSON template path")

    args = parser.parse_args(argv)

    if not args.command:
        parser.print_help()
        return 0

    if args.command == "auto":
        return _cmd_auto(args)
    elif args.command == "read":
        return _cmd_read(args)
    elif args.command == "watch":
        return _cmd_watch(args)
    elif args.command == "serve":
        return _cmd_serve(args)
    elif args.command == "init":
        return _cmd_init(args)

    return 0


if __name__ == "__main__":
    sys.exit(main())
